### ISSUE TITLE
No any option to make Khuluma's stop in between answering

### ISSUE THREAD

**Issue by Kunal-Khairnar-05** [vbookshelf/Khuluma-Javascript-Voicebot-ChatGPT#2]
# No any option to make Khuluma's stop in between answering
---
1. Couldn't stop very long answer being given by Khuluma. 
2. The voice texture model being used sound too much robotic.

**Comment by vbookshelf** [comment]
Hi @Kunal-Khairnar-05. Thanks for your feedback. This project is a basic demo of how to use free tools to create a voicebot. Therefore, I'm not planning to make any improvements to Khuluma. Howvever, you are free to fork this repo and add extra features. As you pointed out, one feature that could be added is the ability to stop long answers. Another feature could be the ability to mute the bot.

Another exciting option would be to combine OpenAi function calls with an Arduino or Raspberry Pi. Then the bot could do things that you tell it to do - by using your voice. For example it could switch on a light. Here's an example project:
https://github.com/vbookshelf/Arduino-Computer-Vision-Finger-Counter

You're correct that the bot's voice does sound robotic. This is because Javascript text to speech is not very advanced, but it is free. You could get a more natural sounding voice by using Google Text-to-Speech or another paid solution.

**Comment by vbookshelf** [comment]
It was quick to do so I've added a feature. Clicking "Quiet please" will mute the bot to stop it from talking.

**Comment by Kunal-Khairnar-05** [comment]
Appreciate your efforts. Good work
